name: codecov

on:
  push:
    paths-ignore:
      - "docs/**"
    branches: [main, develop]
  pull_request:
    paths-ignore:
      - "docs/**"
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: supercharge/mongodb-github-action@1.3.0
      - run: yarn install
      - run: yarn coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
